site_name: Stuff I Find Useful
theme:
  name: readthedocs

nav:
  - Home: index.md
  - Marp Stuff: marp_stuff.md
  - Debian Linux Setup: debian_setup.md
  - VMWare Workstation Notes: vmware_stuff.md
  - Fedora Stuff: fedora_stuff.md
  - Uninstall Snap: uninstall_snap.md
  - Swapt Docker 4 Podman: swap_docker_for_podman.md
  - Machine Transfer: machine_transfer.md
  - Setup SSH for Github: setup_ssh_for_github.md
  - Clear Github Project History: clear_github_project_history.md
  