site_name: Stuff I Find Useful
theme:
  name: readthedocs

nav:
  - Home: index.md
  - Marp Stuff: marp_stuff.md
  - Debian Linux Setup: debian_setup.md
  - VMWare Workstation Notes: vmware_stuff.md
  - Fedora Stuff: fedora_stuff.md
  - Uninstall Snap: uninstall_snap.md
  - Swapt Docker 4 Podman: swap_docker_for_podman.md
